### ISSUE TITLE
Atualizar Jornada Binaria

### ISSUE THREAD

**Issue by Van4ngel2** [UniFil-NPI/apps-unifil#16]
---
title: "Jornada Binaria"
draft: false
language: pt-br
featured_image: https://photos.app.goo.gl/kpz3YBsd1s7mNKkf6
summary: O objetivo deste jogo é fazer o máximo de ponto possível, Os jogadores devem responder corretamente a perguntas relacionadas à programação para acumular pontos.
author: Unifil
categories: Blog
tags: ["CC", "Educação", "Tecnologia", "Cultura", "Entretenimento"] 
linkapp: http://144.22.241.184/login.html
linkweb: https://expch.blogspot.com/
linkvideo: https://youtu.be/ort7CWtSLOk

## Bem vindo ao Jornada Binaria

+ O jogo de Quizz de programação que se passa em um mundo onde os jogadores competem para testar seus conhecimentos em programação, desafiar seus amigos e se tornarem os mestres do código.

Uma breve explicação sobre o tema do jogo "Jogo de Quizz de Programação" é que ele se concentra no emocionante mundo da programação. Os jogadores entram em um cenário onde desafios intelectuais, estratégia e diversão se combinam para testar e aprimorar seus conhecimentos em programação. Nesse jogo, você compete para ver quem se tornará o verdadeiro mestre do código, respondendo a perguntas relacionadas à programação marcando o máximo possível de score. O tema central gira em torno da educação lúdica e do aprendizado de conceitos de programação de uma maneira divertida e envolvente.

+ O objetivo da criação: "Quizz de Programação" é multifacetado e abrange várias metas educacionais, sociais e de entretenimento o motivo da escolha dele para nosso projeto de extensão é

Promover o Aprendizado Divertido, estimular o Interesse em Programação o jogo visa despertar o interesse de jogadores, especialmente jovens, em programação e tecnologia realiza a avaliação de Conhecimento, o jogo permite que os jogadores testem e avaliem seus conhecimentos em programação de uma forma prática, fomenta a Competição Saudável e pode promover a Interação Social

JUSTIFICATIVA:

+ Aprendizado Divertido: Muitas vezes, aprender programação pode ser desafiador e até mesmo intimidante + para iniciantes. Este jogo oferece uma maneira divertida e envolvente de aprender e testar conhecimentos em programação. Transforma um tópico muitas vezes considerado complexo em uma atividade lúdica e agradável.

+ Competição Amigável: A competição é uma motivação poderosa para a aprendizagem. O jogo permite que os participantes competem de maneira amigável, estimulando o desejo de aprender e melhorar.

+ Teste de Conhecimento: O jogo oferece uma oportunidade para os jogadores testarem seus conhecimentos em programação de maneira prática e desafiadora. Responder às perguntas certas é crucial para avançar no jogo, o que incentiva a retenção e a aplicação do conhecimento.

+ Interação Social: Este jogo de tabuleiro promove a interação social entre os jogadores, reunindo amigos, colegas de classe ou colegas de trabalho em torno de um interesse comum: a programação. Isso ajuda a criar um ambiente de aprendizado positivo e estimulante.

+ Variedade de Habilidades: O jogo pode ser adaptado para acomodar uma ampla gama de níveis de habilidade em programação, desde iniciantes até especialistas. Isso significa que ele pode ser uma ferramenta de aprendizado eficaz para uma variedade de públicos.

+ Acessibilidade: Como é um jogo de tabuleiro, não requer acesso a computadores ou dispositivos eletrônicos. Isso torna o jogo acessível a um público mais amplo, incluindo pessoas que podem não ter acesso constante à tecnologia.

+ Diversão e Entretenimento: A principal justificativa para a criação deste jogo é proporcionar diversão e entretenimento aos jogadores. Ele transforma o processo de aprendizado em uma experiência divertida, o que é essencial para manter o interesse e a motivação.

## Links do projeto
  
[Blogger](https://expch.blogspot.com/  "Blogger!")
[GitHub](https://github.com/Van4ngel2/projeto-extensao/tree/main  "GitHub!")
[Video Final](https://youtu.be/ort7CWtSLOk  "Video!")
[Quizz](http://144.22.241.184/login.html "Quizz!")

**Comment by Van4ngel2** [comment]
Troque a imagem atual por essa https://photos.app.goo.gl/kpz3YBsd1s7mNKkf6 por favor, obrigado

**Comment by Eronponce** [comment]
Feito

**Comment by Van4ngel2** [comment]
Bem vindo ao Jornada Binaria nao esta aparecendo, e tem apenas dois botoes disponiveis, eu coloquei tres: linkapp: http://144.22.241.184/login.html
linkweb: https://expch.blogspot.com/
linkvideo: https://youtu.be/ort7CWtSLOk e os link estao errados, no template que eu fiz estao corretos, app é para http://144.22.241.184/login.html, web é para //expch.blogspot.com/ e video é para: https://youtu.be/ort7CWtSLOk
