### ISSUE TITLE
Arrumar template

### ISSUE THREAD

**Issue by VitorPaloco** [UniFil-NPI/apps-unifil#26]
Eron, segue o arquivo de template atualizado, teve algumas coisas que não saiu como queria no template antigo então arrumei. Por favor ajustar.

Projeto: Aprovados

[Template.md](https://github.com/user-attachments/files/17599257/Template.md)

**Comment by tcamis** [comment]
Eron, o projeto deles é o APROVADOS

**Comment by Eronponce** [comment]
Editado
https://apps.unifil.tech/posts/aprovados/
