### ISSUE TITLE
Atualização de Template, e "Acesse o Aplicativo" do app com link errado.

### ISSUE THREAD

**Issue by Nandanuness** [UniFil-NPI/apps-unifil#28]
Boa noite!

Aplicativo Uni HomeMatch:

1. Segue em anexo atualização do template com algumas modificações.
2. Em "Acesse o Aplicativo" na AppStore Unifil está sendo encaminhado para este link http://64.181.190.222:3000/ correspondente ao projeto UniSalas e não o nosso. O link correto é http://144.22.141.202

[Uni HomeMatch.md](https://github.com/user-attachments/files/17671077/Uni.HomeMatch.md)

Obrigado desde já :)

**Comment by Eronponce** [comment]
Feito https://apps.unifil.tech/posts/unihomematch/
