### ISSUE TITLE
Atualização "Job in Job"

### ISSUE THREAD

**Issue by RawannyCanela** [UniFil-NPI/apps-unifil#29]
Inserir link do site: http://168.138.132.44:8081/
Alterar link do vídeo: https://youtu.be/chRIrJL4rgw?feature=shared

**Comment by Eronponce** [comment]
Alterado link do video, do site continua o mesmo que estava antes http://168.138.132.44:8081

**Comment by RawannyCanela** [comment]
o botão com o link do site ainda não aparece na loja. ..

Em ter., 19 de nov. de 2024, 16:52, Eron ***@***.***>
escreveu:

**Comment by Eronponce** [comment]
Ok, com o problema entendido "botao nao aprarece", consegui resolver, não existe no template disponibilizado o caminho de variável  ---> `linkapp` 
mas sim,
linkandroid: link  de download do aplicativo em android
linkios: link de download aplicativo em ios
linkweb: link de acesso de aplicativo web
linkblog: Link do blog
linkvideo: Link do video

Por conta deste motivo nao existia o botao no site. modifquei para 
linkweb: http://168.138.132.44:8081
